### ISSUE TITLE
Exposed Google Cloud API Key & Spotify id+secret

### ISSUE THREAD

**Issue by x1mdev** [dudaMeneses/quantas-vezes-ela-partiu#1]
Potential security breach. See /src/main/resources/external.yml #

**Comment by x1mdev** [comment]
https://open.spotify.com/artist/0jOs0wnXCu1bGGP7kh5uIu nice tunes tho :)

**Comment by dudaMeneses** [comment]
thank you dude! I already removed that :)

**Comment by x1mdev** [comment]
Nice :)
